vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        actor_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
